// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/exam/exam.proto

package com_lcb123_srv_exam

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Exam service

type ExamService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Exam_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Exam_PingPongService, error)
}

type examService struct {
	c    client.Client
	name string
}

func NewExamService(name string, c client.Client) ExamService {
	return &examService{
		c:    c,
		name: name,
	}
}

func (c *examService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Exam.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Exam_StreamService, error) {
	req := c.c.NewRequest(c.name, "Exam.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &examServiceStream{stream}, nil
}

type Exam_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type examServiceStream struct {
	stream client.Stream
}

func (x *examServiceStream) Close() error {
	return x.stream.Close()
}

func (x *examServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *examServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *examServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *examServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *examService) PingPong(ctx context.Context, opts ...client.CallOption) (Exam_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Exam.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &examServicePingPong{stream}, nil
}

type Exam_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type examServicePingPong struct {
	stream client.Stream
}

func (x *examServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *examServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *examServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *examServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *examServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *examServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Exam service

type ExamHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Exam_StreamStream) error
	PingPong(context.Context, Exam_PingPongStream) error
}

func RegisterExamHandler(s server.Server, hdlr ExamHandler, opts ...server.HandlerOption) error {
	type exam interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Exam struct {
		exam
	}
	h := &examHandler{hdlr}
	return s.Handle(s.NewHandler(&Exam{h}, opts...))
}

type examHandler struct {
	ExamHandler
}

func (h *examHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.ExamHandler.Call(ctx, in, out)
}

func (h *examHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.ExamHandler.Stream(ctx, m, &examStreamStream{stream})
}

type Exam_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type examStreamStream struct {
	stream server.Stream
}

func (x *examStreamStream) Close() error {
	return x.stream.Close()
}

func (x *examStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *examStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *examStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *examStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *examHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.ExamHandler.PingPong(ctx, &examPingPongStream{stream})
}

type Exam_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type examPingPongStream struct {
	stream server.Stream
}

func (x *examPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *examPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *examPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *examPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *examPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *examPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
