// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/admin/admin.proto

package com_lcb123_srv_admin

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Admin service

type AdminService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Admin_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Admin_PingPongService, error)
}

type adminService struct {
	c    client.Client
	name string
}

func NewAdminService(name string, c client.Client) AdminService {
	return &adminService{
		c:    c,
		name: name,
	}
}

func (c *adminService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Admin.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Admin_StreamService, error) {
	req := c.c.NewRequest(c.name, "Admin.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &adminServiceStream{stream}, nil
}

type Admin_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type adminServiceStream struct {
	stream client.Stream
}

func (x *adminServiceStream) Close() error {
	return x.stream.Close()
}

func (x *adminServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *adminServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *adminServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *adminServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *adminService) PingPong(ctx context.Context, opts ...client.CallOption) (Admin_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Admin.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &adminServicePingPong{stream}, nil
}

type Admin_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type adminServicePingPong struct {
	stream client.Stream
}

func (x *adminServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *adminServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *adminServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *adminServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *adminServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *adminServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Admin service

type AdminHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Admin_StreamStream) error
	PingPong(context.Context, Admin_PingPongStream) error
}

func RegisterAdminHandler(s server.Server, hdlr AdminHandler, opts ...server.HandlerOption) error {
	type admin interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Admin struct {
		admin
	}
	h := &adminHandler{hdlr}
	return s.Handle(s.NewHandler(&Admin{h}, opts...))
}

type adminHandler struct {
	AdminHandler
}

func (h *adminHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.AdminHandler.Call(ctx, in, out)
}

func (h *adminHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.AdminHandler.Stream(ctx, m, &adminStreamStream{stream})
}

type Admin_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type adminStreamStream struct {
	stream server.Stream
}

func (x *adminStreamStream) Close() error {
	return x.stream.Close()
}

func (x *adminStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *adminStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *adminStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *adminStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *adminHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.AdminHandler.PingPong(ctx, &adminPingPongStream{stream})
}

type Admin_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type adminPingPongStream struct {
	stream server.Stream
}

func (x *adminPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *adminPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *adminPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *adminPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *adminPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *adminPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
